---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hurunagus-silverblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: os-release
    properties:
      ID: hurunagus-silverblue
      ID_LIKE: fedora
      NAME: hurunagus-silverblue
      PRETTY_NAME: hurunagus-silverblue
      VERSION_CODENAME: hurunagus-silverblue
      DEFAULT_HOSTNAME: hurunagas33
      
  
  - type: gnome-extensions
    install:
      - Blur my Shell
      - Dash to Panel
      - GSConnect
      - Logo Menu
      
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - btop
        - fastfetch
        #- starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - gnome-software
        - gnome-system-monitor
      
    #- type: gnome-extensions
    #install:
      #- Blur my Shell 
      #- Alphabetical App Grid
      #- 779 # Clipboard Indicator
      #- Focused Window D-Bus
      #- Run or raise
      #- Rounded Window Corners Reborn
      #- Tiling Assistant
         
  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
         - org.mozilla.firefox
         - org.audacityteam.Audacity
         - com.bitwig.BitwigStudio
         - org.blender.Blender
         - com.brave.Browser
         - org.chromium.Chromium
         - de.leopoldluley.Clapgrep
         - org.gimp.GIMP
         - org.kde.kdenlive
         - com.obsproject.Studio
         - re.sonny.Retro
         - org.videolan.VLC
         - org.libreoffice.LibreOffice
         - org.pitivi.Pitivi
         - fr.handbrake.ghb
         - io.gitlab.theevilskeleton.Upscaler
         - com.github.wwmm.easyeffects
         - org.thentrythis.Samplebrain
         - net.biniou.LeBiniou
         - com.github.zocker_160.SyncThingy
         - org.kde.kate
         - org.kde.okular
         - org.mixxx.Mixxx
         - org._3fz.mtoc
         - org.luanti.luanti
         - org.vinegarhq.Sober
         - net.supertuxkart.SuperTuxKart
         - org.kde.kpat
         - org.gnome.Chess
         - org.gnome.Maps
         - org.nongnu.lingot
         - com.dec05eba.gpu_screen_recorder
         - com.github.polymeilex.neothesia
         - com.rafaelmardojai.Blanket
         - me.timschneeberger.jdsp4linux
         - org.inkscape.Inkscape
         - org.virt_manager.virt-manager
         - io.missioncenter.MissionCenter
         - io.github.kolunmi.Bazaar
         - com.mattjakeman.ExtensionManager
         - com.github.tchx84.Flatseal
         
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
