---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hurunagus-silverblue
# description will be included in the image's metadata
description: Custom Silverblue with Niri + DMS.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: fonts
    fonts:
      google-fonts:
      #- Roboto
      #- Open Sans
      - Inter
      #- Roboto Mono
      #- Google Sans
      #- Ubuntu

  - type: gnome-extensions
    install:
      - Blur my Shell
      - Dash to Panel
      #- GSConnect
      - Logo Menu
      
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - btop
        - fastfetch
        - gnome-tweaks
        #- gnome-backgrounds-extras
        #- scx-scheds
        #- scx-tools
        #- scx-manager
        - niri
        - foot
        #- greetd
        #- dankcalendar-bin
        #- dsearch
        - khal
        #- usbmuxd
        - adwaita-fonts-all
        - igt-gpu-tools
        - google-noto-sans-fonts
        - google-noto-serif-fonts
        - google-noto-sans-mono-fonts
        - lm_sensors
        #- rclone
        #- rclone-browser
    remove:
      packages:
        - gnome-software
        - gnome-system-monitor
        - gnome-tour
        #- thunderbird
      


  - type: dnf
    repos:
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    install:
      packages:
        - brave-origin

  - type: dnf
    repos:
      copr:
        - avengemedia/dms
    install:
      packages:
        - dms
        - dsearch
        - dms-greeter
        - qt6ct-kde
        - dankcalendar-git


  - type: gschema-overrides
  
   #Cachyos kernel --- ***currently disabled***
  #- type: custom-kernel
    #source: local
    #kernel: cachyos
    #initramfs: true
    #nvidia: false
    
  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
        # - org.mozilla.firefox
         #- org.audacityteam.Audacity
         - com.bitwig.BitwigStudio
         - org.blender.Blender
         - com.brave.Browser
         - org.chromium.Chromium
         #- de.leopoldluley.Clapgrep
         - org.fedoraproject.MediaWriter
         - org.gimp.GIMP
         - org.kde.kdenlive
         - com.obsproject.Studio
         #- re.sonny.Retro
         - org.videolan.VLC
         #- org.libreoffice.LibreOffice
         #- org.pitivi.Pitivi
         #- fr.handbrake.ghb
         #- io.gitlab.theevilskeleton.Upscaler
         - com.github.wwmm.easyeffects
         #- org.thentrythis.Samplebrain
         #- net.biniou.LeBiniou
         #- com.github.zocker_160.SyncThingy
         - org.kde.kate
         - org.kde.okular
         - org.mixxx.Mixxx
         #- org._3fz.mtoc
         #- org.luanti.luanti
         #- org.vinegarhq.Sober
         - net.supertuxkart.SuperTuxKart
         - org.kde.kpat
         - org.gnome.Chess
         - org.gnome.Maps
         #- org.nongnu.lingot
         #- com.dec05eba.gpu_screen_recorder
         #- com.github.polymeilex.neothesia
         #- com.rafaelmardojai.Blanket
         #- me.timschneeberger.jdsp4linux
         #- org.inkscape.Inkscape
         - org.virt_manager.virt-manager
         - org.virt_manager.virt_manager.Extension.Qemu
         - io.missioncenter.MissionCenter
         - io.github.kolunmi.Bazaar
         - com.mattjakeman.ExtensionManager
         - com.github.tchx84.Flatseal
         #- org.altlinux.Tuner
         - io.github.shiftey.Desktop
         #- be.alexandervanhee.gradia
         
      # - scope: user # Also add Flathub user repo, but no user packages

  - type: script
    scripts:
         - bpfland.sh

  - type: os-release
    properties:
      ID: hurunagus-silverblue
      ID_LIKE: fedora
      NAME: hurunagus-silverblue
      PRETTY_NAME: hurunagus-silverblue
      VERSION_CODENAME: hurunagus-silverblue
      DEFAULT_HOSTNAME: hurunagas33

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
